Repository GSM-MSG/GAuth-BackEnd, pull requests merged in 2023-12, with the labels that each got.

#229 deleted::불필요한 import문 삭제
  src/main/kotlin/com/msg/gauth/domain/client/Client.kt
  src/main/kotlin/com/msg/gauth/domain/client/repository/CustomClientRepositoryImpl.kt
  src/main/kotlin/com/msg/gauth/domain/client/service/DeleteClientsService.kt
  src/main/kotlin/com/msg/gauth/domain/client/service/RegisterClientService.kt
  src/main/kotlin/com/msg/gauth/domain/client/service/UpdateAnyClientService.kt
  src/main/kotlin/com/msg/gauth/domain/client/service/UpdateClientService.kt
  src/main/kotlin/com/msg/gauth/domain/image/presentation/ImageController.kt
  src/main/kotlin/com/msg/gauth/domain/image/service/UploadImageService.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/AcceptStudentSignUpService.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/AcceptUserSignUpService.kt
  src/main/kotlin/com/msg/gauth/global/exception/handler/GlobalExceptionHandler.kt
  src/main/kotlin/com/msg/gauth/global/filter/ExceptionFilter.kt
  src/main/kotlin/com/msg/gauth/global/filter/RequestLogFilter.kt
  src/main/kotlin/com/msg/gauth/global/thirdparty/mail/MailConfig.kt
  src/main/kotlin/com/msg/gauth/global/thirdparty/mail/properties/MailProperties.kt
Labels: 🔨 Refactor

#231 🔀 ::healthCheck api 추가
  src/main/kotlin/com/msg/gauth/domain/health/presentation/HealthCheckController.kt
  src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
Labels: 0️⃣Priority: Critical, 📬 API

#233 🔀 :: 232 UserRole 엔티티 추가
  src/main/kotlin/com/msg/gauth/domain/auth/service/SignUpService.kt
  src/main/kotlin/com/msg/gauth/domain/user/User.kt
  src/main/kotlin/com/msg/gauth/domain/user/UserRole.kt
  src/main/kotlin/com/msg/gauth/domain/user/enums/UserRoleType.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptTeacherReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptUserReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptedUserRequest.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/response/GetMyRolesResDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepositoryImpl.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/UserRepository.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/UserRoleRepository.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/AcceptStudentSignUpService.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/AcceptTeacherSignUpService.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/AcceptUserSignUpService.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/GetAcceptedUsersService.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/GetMyRolesService.kt
Labels: 🔨 Refactor, 2️⃣Priority: Medium

#235 🔀::WebHook 로직 추가
  Task
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  src/main/kotlin/com/msg/gauth/domain/auth/event/SignupLoggingEvent.kt
  src/main/kotlin/com/msg/gauth/domain/auth/handler/AuthEventHandler.kt
  src/main/kotlin/com/msg/gauth/domain/auth/service/SignUpService.kt
  src/main/kotlin/com/msg/gauth/global/thirdparty/discord/properties/DiscordProperties.kt
  src/main/resources/application.yml
  src/test/kotlin/com/msg/gauth/GauthBackendApplicationTests.kt
Labels: 📬 API, 3️⃣Priority: Low, ✨ Feature

#237 🔀::서비스 대표자 위임 API
  src/main/kotlin/com/msg/gauth/domain/client/exception/BadDelegateUserIdRequestException.kt
  src/main/kotlin/com/msg/gauth/domain/client/presentation/ClientController.kt
  src/main/kotlin/com/msg/gauth/domain/client/service/DelegateOwnerService.kt
  src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
Labels: 📬 API, 2️⃣Priority: Medium, ✨ Feature

#239 🔀::emded에 url추가
  src/main/kotlin/com/msg/gauth/domain/auth/handler/AuthEventHandler.kt
Labels: 🔨 Refactor

#241 :twisted_rightwards_arrows: :: appspec.yml 추가
  appspec.yml
Labels: 1️⃣Priority: High, 🌏 Deploy
