Repository GSM-MSG/GAuth-BackEnd, pull requests merged in 2023-09, with the labels that each got.

#212 :bug: :: if 조건식이 반대로 되어있었던 버그 수정
  src/main/kotlin/com/msg/gauth/domain/image/service/UploadImageService.kt
Labels: 0️⃣Priority: Critical, 🐞 BugFix, ⚡️ Simple

#214 🔀 :: 마이페이지 response에 클라 이미지 url 추가
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/response/MyProfileResDto.kt
Labels: 3️⃣Priority: Low, ⚡️ Simple

#216 🔀 :: multipart request 용량 5MB로 증대
  src/main/resources/application.yml
Labels: 2️⃣Priority: Medium

#219 🔀 :: 핸들링 되지 않은 에러 발생 시 에러 원인 로깅
  src/main/kotlin/com/msg/gauth/global/filter/ExceptionFilter.kt
  src/main/kotlin/com/msg/gauth/global/filter/RequestLogFilter.kt
Labels: 0️⃣Priority: Critical

#221 refactor :: OAuthTokenProvider, JwtTokenProvider 공통 parseToken 로직 분리
  src/main/kotlin/com/msg/gauth/domain/auth/service/RefreshService.kt
  src/main/kotlin/com/msg/gauth/domain/oauth/OauthCode.kt
  src/main/kotlin/com/msg/gauth/domain/oauth/repository/OauthCodeRepository.kt
  src/main/kotlin/com/msg/gauth/domain/oauth/service/GenerateOauthCodeService.kt
  src/main/kotlin/com/msg/gauth/domain/oauth/service/RefreshOauthTokenService.kt
  src/main/kotlin/com/msg/gauth/global/filter/JwtTokenFilter.kt
  src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
  src/main/kotlin/com/msg/gauth/global/security/config/FilterConfig.kt
  src/main/kotlin/com/msg/gauth/global/security/jwt/JwtTokenProvider.kt
  src/main/kotlin/com/msg/gauth/global/security/jwt/OauthTokenProvider.kt
  src/main/kotlin/com/msg/gauth/global/security/jwt/TokenParser.kt
Labels: 🔨 Refactor, 1️⃣Priority: High
