Repository GSM-MSG/GAuth-BackEnd, pull requests merged in 2023-04, with the labels that each got.

#136 135 user accept api
  src/main/kotlin/com/msg/gauth/domain/auth/presentation/AuthController.kt
  src/main/kotlin/com/msg/gauth/domain/client/exception/BadUserRoleRequestException.kt
  src/main/kotlin/com/msg/gauth/domain/user/User.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptTeacherReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptUserReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/UserRepository.kt
  src/main/kotlin/com/msg/gauth/domain/user/services/AcceptStudentSignUpService.kt
  src/main/kotlin/com/msg/gauth/domain/user/services/AcceptTeacherSignUpService.kt
  src/main/kotlin/com/msg/gauth/domain/user/services/AcceptUserSignUpService.kt
  src/main/kotlin/com/msg/gauth/global/exception/ErrorCode.kt
  src/main/kotlin/com/msg/gauth/global/exception/exceptions/BadRequestException.kt
  src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
Labels: ✨ Feature

#137 🔀 :: 108 - oauth토큰 발급시 oauth코드 지우기
  src/main/kotlin/com/msg/gauth/domain/oauth/presentation/OauthController.kt
  src/main/kotlin/com/msg/gauth/domain/oauth/presentation/dto/request/OauthTokenRequestDto.kt
  src/main/kotlin/com/msg/gauth/domain/oauth/presentation/dto/response/OauthTokenResponseDto.kt
  src/main/kotlin/com/msg/gauth/domain/oauth/services/GenerateOauthCodeService.kt
  src/main/kotlin/com/msg/gauth/domain/oauth/services/GenerateOauthTokenService.kt
  src/main/kotlin/com/msg/gauth/domain/oauth/services/RefreshOauthTokenService.kt
Labels: 1️⃣Priority: High, ⚡️ Simple

#139 유저 회원가입 수락에 졸업생 수락 기능 추가
  src/main/kotlin/com/msg/gauth/domain/user/User.kt
  src/main/kotlin/com/msg/gauth/domain/user/enums/UserRole.kt
  src/main/kotlin/com/msg/gauth/domain/user/services/AcceptTeacherSignUpService.kt
  src/main/kotlin/com/msg/gauth/domain/user/services/AcceptUserSignUpService.kt
Labels: ✨ Feature

#142 🔀 :: 84 - codeowners 세팅
  .github/CODEOWNERS
Labels: ⚙ Setting, 3️⃣Priority: Low, ⚡️ Simple

#144 가입된 유저 검색 서비스 리팩터링
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  buildSrc/src/main/kotlin/PluginVersion.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepository.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepositoryImpl.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/UserRepository.kt
  src/main/kotlin/com/msg/gauth/domain/user/services/GetAcceptedUsersService.kt
  src/main/kotlin/com/msg/gauth/global/querydsl/QuerydslConfig.kt
  src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
Labels: 🔨 Refactor

#149 유저 회원가입 거절 api
  src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
  src/main/kotlin/com/msg/gauth/domain/user/services/RejectUserSignUpService.kt
  src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
Labels: ✨ Feature

#153 :recycle: :: booleanExpression 사용
  src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepositoryImpl.kt
Labels: 🔨 Refactor
