Repository GSM-MSG/GAuth-BackEnd, pull requests merged in 2023-03, with the labels that each got.

#94 패스워드 정규식 수정
  src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/PasswordInitReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/SignupRequestDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/PasswordChangeReqDto.kt
Labels: 0️⃣Priority: Critical, ⚡️ Simple

#99 🔀 ::98 - 이미지 업로드가 안되던 버그
  src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
Labels: 0️⃣Priority: Critical, 🐞 BugFix

#106 아니 프론트가 상의도 없이 accessToken으로 code발급받는 API 만들라함;;
  src/main/kotlin/com/msg/gauth/domain/oauth/presentation/OauthController.kt
  src/main/kotlin/com/msg/gauth/domain/oauth/services/OauthCodeService.kt
  src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
Labels: 0️⃣Priority: Critical, 📬 API, ✨ Feature

#107 🔀 :: 이메일 전송 템플릿 변경
  build.gradle.kts
  src/main/kotlin/com/msg/gauth/domain/email/presentation/EmailController.kt
  src/main/kotlin/com/msg/gauth/domain/email/services/MailSendService.kt
  src/main/kotlin/com/msg/gauth/global/mail/MailConfig.kt
  src/main/resources/templates/mail.html
Labels: 0️⃣Priority: Critical, 🔨 Refactor, ✨ Feature

#110 🔀 :: 109 ci/cd
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
Labels: 2️⃣Priority: Medium, ✨ Feature, 🌏 Deploy

#112 🔀 :: 이메일 템플릿 오류
  src/main/kotlin/com/msg/gauth/domain/email/services/MailSendService.kt
  src/main/kotlin/com/msg/gauth/global/mail/MailConfig.kt
  src/main/kotlin/com/msg/gauth/global/thymeleaf/ThymeleafConfig.kt
  src/main/resources/templates/mail-template.html
Labels: 0️⃣Priority: Critical, 🐞 BugFix

#114 🔀 :: 프론트 개발섭의 cors 허용
  src/main/kotlin/com/msg/gauth/global/web/WebMvcConfig.kt
Labels: 1️⃣Priority: High, 🌏 Deploy

#118 🔀 :: 117 - 쿼리 줄이기
  src/main/kotlin/com/msg/gauth/domain/admin/services/ExcelParsingService.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/UserRepository.kt
Labels: 🔨 Refactor, 3️⃣Priority: Low

#120 🔀 :: 현재 본인의 Role을 가져오는 API
  scaffold.py
  src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/response/GetMyRolesResDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/services/GetMyRolesService.kt
Labels: 0️⃣Priority: Critical

#124 🔀 :: 123 - log4k 개선
  build.gradle.kts
  src/main/kotlin/com/msg/gauth/domain/email/services/MailSendService.kt
  src/main/kotlin/com/msg/gauth/global/annotation/logger/InjectionLogger.kt
  src/main/kotlin/com/msg/gauth/global/annotation/logger/InjectorLogger.kt
  src/main/kotlin/com/msg/gauth/global/annotation/logger/log4k.kt
  src/main/kotlin/com/msg/gauth/global/exception/handler/GlobalExceptionHandler.kt
Labels: 🔨 Refactor, 3️⃣Priority: Low
