Repository GSM-MSG/GAuth-BackEnd, pull requests merged in 2024-02, with the labels that each got.

#261 🔀 Update :: appspec.yml
  appspec.yml
Labels: ⚡️ Simple, 🌏 Deploy

#263 🔀 :: golang를 사용한 accessToken 갱신 스크립트
  renew_jwt.go
Labels: 2️⃣Priority: Medium

#269 🔀 :: CODEOWNERS에 저를 추가
  .github/CODEOWNERS
Labels: ⚙ Setting, 3️⃣Priority: Low

#267 🔀 :: 266 CI/CD 기준 브랜치 변경
  .github/workflows/Gauth-CD.yml
  .github/workflows/ci.yml
Labels: 0️⃣Priority: Critical, 🌏 Deploy

#272 🔀 :: update deploy.sh
  deploy.sh
Labels: ⚡️ Simple, 🌏 Deploy
