Repository GSM-MSG/GAuth-BackEnd, pull requests merged in 2024-01, with the labels that each got.

#243 :twisted_rightwards_arrows: :: deploy.sh 파일 추가
  deploy.sh
Labels: 🌏 Deploy

#245 🔀 :: 테이블명 중복 제거
  src/main/kotlin/com/msg/gauth/domain/user/User.kt
Labels: 🐞 BugFix

#247 🔀 :: UserRole 엔티티 대신 collection table 사용
  src/main/kotlin/com/msg/gauth/domain/user/service/GetMyRolesService.kt
Labels: 0️⃣Priority: Critical, ⚡️ Simple

#249 🔥 :: 클타용 deploy.sh 파일 삭제
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#251 🔀 :: 250 DB Driver class와 platform 환경변수로 관리
  src/main/resources/application.yml
Labels: 0️⃣Priority: Critical, ⚡️ Simple

#253 🔀 create :: Gauth-CD.yml 파일 생성
  .github/workflows/Gauth-CD.yml
Labels: 1️⃣Priority: High, ✨ Feature, 🌏 Deploy

#255 🔀 Update :: Gauth-CD.yml
  .github/workflows/Gauth-CD.yml
Labels: 1️⃣Priority: High, 🐞 BugFix, 🌏 Deploy

#257 🔀 update :: Gauth-CD 정상적으로 작동되게끔 수정
  .github/workflows/Gauth-CD.yml
Labels: 1️⃣Priority: High, 🐞 BugFix, 🌏 Deploy
