Repository GSM-MSG/GAuth-BackEnd, pull requests merged in 2024-04, with the labels that each got.

#307 🔀 :: CD 스크립트 수정
  appspec.yml
  deploy.sh
Labels: 1️⃣Priority: High, 🌏 Deploy

#309 🔀 :: 새로운 pull request template 적용
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙ Setting, ⚡️ Simple

#311 🔀 :: 변경 시 리소스서버 반영 확인 체크리스트 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 0️⃣Priority: Critical, ⚙ Setting

#313 🔀 :: cors url 추가
  src/main/kotlin/com/msg/gauth/global/config/web/WebMvcConfig.kt
Labels: 0️⃣Priority: Critical

#315 🔀 :: cors url 변경
  src/main/kotlin/com/msg/gauth/global/config/web/WebMvcConfig.kt
Labels: 0️⃣Priority: Critical

#317 🔀 :: 이메일 인증 url 변경
  src/main/kotlin/com/msg/gauth/domain/email/service/SendMailService.kt
Labels: 1️⃣Priority: High, 🐞 BugFix
