Repository GSM-MSG/GAuth-BackEnd, pull requests merged in 2024-03, with the labels that each got.

#270 🔀 :: 265 user list N+1 개선
  src/main/kotlin/com/msg/gauth/domain/admin/service/ExcelParsingService.kt
  src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/PasswordInitReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/auth/service/SignUpService.kt
  src/main/kotlin/com/msg/gauth/domain/user/User.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptStudentReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptTeacherReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptUserReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/PasswordChangeReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepositoryImpl.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/UserRepository.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/GetMyRolesService.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/UploadProfileService.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/UploadProfileURLService.kt
  src/main/kotlin/com/msg/gauth/domain/user/util/TempUserUtil.kt
  src/main/kotlin/com/msg/gauth/global/security/auth/AuthDetails.kt
  src/main/kotlin/com/msg/gauth/global/util/count/auth/util/TooManyRequestValidUtil.kt
  src/main/kotlin/com/msg/gauth/global/util/count/oauth/util/TooManyOAuthRequestValidUtil.kt
Labels: 🔨 Refactor, 1️⃣Priority: High

#274 🔀 update :: deploy.sh
  deploy.sh
Labels: ⚡️ Simple, 🌏 Deploy

#276 🔀 ::275 user와 UserRole 양방향 매핑 삭제
  src/main/kotlin/com/msg/gauth/domain/admin/service/ExcelParsingService.kt
  src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/PasswordInitReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/auth/service/SignUpService.kt
  src/main/kotlin/com/msg/gauth/domain/user/User.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptStudentReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptTeacherReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/AcceptUserReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/request/PasswordChangeReqDto.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepositoryImpl.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/UserRepository.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/UserRoleRepository.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/GetMyRolesService.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/UploadProfileService.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/UploadProfileURLService.kt
  src/main/kotlin/com/msg/gauth/domain/user/util/TempUserUtil.kt
  src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
  src/main/kotlin/com/msg/gauth/global/security/auth/AuthDetails.kt
  src/main/kotlin/com/msg/gauth/global/security/auth/AuthDetailsService.kt
  src/main/kotlin/com/msg/gauth/global/util/count/auth/util/TooManyRequestValidUtil.kt
  src/main/kotlin/com/msg/gauth/global/util/count/oauth/util/TooManyOAuthRequestValidUtil.kt
Labels: 0️⃣Priority: Critical, 🐞 BugFix

#278 add :: broken uri patterns
  src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
Labels: 0️⃣Priority: Critical, ⚡️ Simple

#281 🔀 :: 280 User의 UserRole 프로퍼티 롤백
  src/main/kotlin/com/msg/gauth/domain/user/User.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/UserRepository.kt
  src/main/kotlin/com/msg/gauth/domain/user/repository/UserRoleRepository.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/GetMyRolesService.kt
  src/main/kotlin/com/msg/gauth/global/security/auth/AuthDetails.kt
  src/main/kotlin/com/msg/gauth/global/security/auth/AuthDetailsService.kt
Labels: 0️⃣Priority: Critical, 🔨 Refactor

#284 🔀 :: 서비스 소유자 위임 중 재학생 검증 로직
  src/main/kotlin/com/msg/gauth/domain/client/exception/InvalidDelegateUserException.kt
  src/main/kotlin/com/msg/gauth/domain/client/service/DelegateOwnerService.kt
  src/main/kotlin/com/msg/gauth/global/exception/ErrorCode.kt
Labels: 1️⃣Priority: High

#289 🔀 :: my profile response dto에 id추가
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/response/MyProfileResDto.kt
Labels: ⚡️ Simple

#291 🔀 :: id 표기 수정
  src/main/kotlin/com/msg/gauth/domain/user/presentation/dto/response/MyProfileResDto.kt
Labels: ⚡️ Simple

#293 🔀 :: 서비스 위임자 권한 로직 수정
  src/main/kotlin/com/msg/gauth/domain/client/service/DelegateOwnerService.kt
Labels: 1️⃣Priority: High

#295 🔀 :: 유저 리스트 동적인 정렬 처리
  src/main/kotlin/com/msg/gauth/domain/user/repository/CustomUserRepositoryImpl.kt
Labels: 2️⃣Priority: Medium

#297 🔀 :: 비밀번호 재설정 기능 추가
  src/main/kotlin/com/msg/gauth/domain/auth/presentation/AuthController.kt
  src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/PasswordUpdateRequestDto.kt
  src/main/kotlin/com/msg/gauth/domain/auth/service/UpdatePasswordService.kt
  src/main/kotlin/com/msg/gauth/global/security/SecurityConfig.kt
Labels: 1️⃣Priority: High, ✨ Feature

#299 🔀 :: application.yml overwrite job
  .github/workflows/Gauth-CD.yml
  .github/workflows/ci.yml
Labels: ⚡️ Simple, 🌏 Deploy

#301 🔀 :: 기존 비밀번호와 새 비밀번호와 다른지 검사하는 로직
  src/main/kotlin/com/msg/gauth/domain/auth/exception/PasswordAndNewPasswordSameException.kt
  src/main/kotlin/com/msg/gauth/domain/auth/presentation/AuthController.kt
  src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/InitPasswordRequestDto.kt
  src/main/kotlin/com/msg/gauth/domain/auth/presentation/dto/request/UpdatePasswordRequestDto.kt
  src/main/kotlin/com/msg/gauth/domain/auth/service/InitPasswordService.kt
  src/main/kotlin/com/msg/gauth/domain/auth/service/UpdatePasswordService.kt
  src/main/kotlin/com/msg/gauth/global/exception/ErrorCode.kt
Labels: 🔨 Refactor, 1️⃣Priority: High

#303 🔀 :: 쓰이지 않는 프로필 업로드 api 삭제
  src/main/kotlin/com/msg/gauth/domain/user/presentation/UserController.kt
  src/main/kotlin/com/msg/gauth/domain/user/service/UploadProfileService.kt
Labels: 2️⃣Priority: Medium

#305 🔀 :: 회원가입시 이미지 확장자 검사 로직
  src/main/kotlin/com/msg/gauth/domain/auth/presentation/AuthController.kt
  src/main/kotlin/com/msg/gauth/domain/auth/service/SignUpImageUploadService.kt
  src/main/kotlin/com/msg/gauth/domain/image/service/UploadImageService.kt
  src/main/kotlin/com/msg/gauth/global/thirdparty/aws/s3/S3Util.kt
Labels: 🔨 Refactor, 1️⃣Priority: High
